{
    "result":
    {
        "profile":
        {
            "username":"inative",
            "trade_password_enabled":true,
            "otp_enabled":false,
            "trade_fee":0,
            "trade_fee_cnyltc":0,
            "trade_fee_btcltc":0,
            "daily_btc_limit":10,
            "daily_ltc_limit":400,
            "btc_deposit_address":"1TFj8jfgABid5u7v2RmRY8rA7ZBFishup",
            "btc_withdrawal_address":"",
            "ltc_deposit_address":"Lg3WtqQuvCFCJ7VAxBSSXDsqcDMQSu31vb",
            "ltc_withdrawal_address":"",
            "api_key_permission":3
        },
        "balance":
        {
            "btc":
            {
                "currency":"BTC",
                "symbol":"\u0e3f",
                "amount":"0.00000000",
                "amount_integer":"0",
                "amount_decimal":8
            },
            "ltc":
            {
                "currency":"LTC",
                "symbol":"\u0141",
                "amount":"0.00076000",
                "amount_integer":"76000",
                "amount_decimal":8
            },
            "cny":
            {
                "currency":"CNY",
                "symbol":"\u00a5",
                "amount":"4706.23164",
                "amount_integer":"470623163",
                "amount_decimal":5
            }
        },
        "frozen":
        {
            "btc":
            {
                "currency":"BTC",
                "symbol":"\u0e3f",
                "amount":"1.73330000",
                "amount_integer":"173330000",
                "amount_decimal":8
            },
            "ltc":
            {
                "currency":"LTC",
                "symbol":"\u0141",
                "amount":"0.00000000",
                "amount_integer":"0",
                "amount_decimal":8
            },
            "cny":
            {
                "currency":"CNY",
                "symbol":"\u00a5",
                "amount":"0.00000",
                "amount_integer":"0",
                "amount_decimal":5
            }
        }
    },
    "id":"1"
}
